# 知识库持续集成，自动发布ericliuhusky.github.io网站
name: Deploy Website CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          yarn install
          yarn docs:build

      - name: Deploy
        run: |
          cd docs/.vuepress/dist
          git init
          git add -A
          git commit -m 'deploy'
